#from exception_test import greet as greet_exc
from exception_test import *
# def greet():
#     print("It's greet")

greet('Student')
print(GREETING)
print(BadName)
print(_GREETING)
# print(greet_exc('Student'))
